import streamlit as st
st.sidebar.title('Menu')
paginaSelecionada = st.sidebar.selectbox('Selecione a página',['INÍCIO', 'SAÚDE E SEUS EFEITOS', 'ALIMENTAÇÃO','EXERCÍCIOS', 'DIETAS' ])
if paginaSelecionada == 'INÍCIO':
 st.title('INÍCIO')
 st.write('A saúde é um equilíbrio dentro de uma pessoa, suas funções e habilidades dependem em grande parte de como ela cuida de si mesma. Isso afeta sua qualidade de vida ou até mesmo sua capacidade de realizar seus sonhos. Além disso, é uma forma de melhorar a condição física, mental e tanto na vida pessoal quanto profissional.')
 st.image("https://wp.cuidar.me/wp-content/uploads/2021/06/beneficios-da-atividade-fisica-para-a-saude-scaled.jpg")
if paginaSelecionada == 'SAÚDE E SEUS EFEITOS':
 st.title('SAÚDE E SEUS EFEITOS')
 st.write('Muitas pessoas pensam que saúde é apenas alimentação, mas é muito mais do que isso. Saúde refere-se à qualidade de vida de cada pessoa e à forma como cuida do seu corpo. Boa saúde significa uma estrutura física e mental positiva, mas a falta dela leva a muitas doenças. Vamos dar uma olhada nos benefícios e malefícios que eles podem causar à sua saúde')
 st.header("BENEFÍCIOS")
 st.write('Segundo a OMS, qualidade de vida é “a visão do indivíduo de sua inserção na vida, no contexto de culturas e sistemas de valores nos quais ele vive e em relação a suas metas, expectativas, padrões e imaginação”. Envolvendo o bem estar espiritual, físico, mental, psicológico e emocional, além de relações sociais, como família e amigos e, também, saúde, educação, moradia, saneamento básico e outras características da vida.')
 st.write('É extremamente recomendado que as pessoas adotem hábitos saudáveis: como se alimentar de maneira saudável; não fumar; evitar café e bebidas alcoólicas de maneira exagerada, não dirija após ingerir bebida alcoólica; busque dormir 8 horas por dia; pratique esportes e procure lazer regularmente; resolva problemas de maneira lógica, encarando-os positivamente; administre seu tempo fazendo uma coisa de cada vez e cultive o bom humor.')
 st.image("https://www.ortopediaalianca.com.br/wp-content/uploads/2018/02/plano-de-saude-gratuito.jpg")
 st.write("No trabalho, programe e tire férias anuais, quando possível, não leve estresse de trabalho para casa; mantenha seu local de trabalho limpo, iluminado, bem ventilado, sem cigarros, poluição ou barulho excessivo; em momentos de tensão faça um procedimento de respiração lenta e pausada, para se acalmar.")
 st.write("No esporte ou Lazer: Faça no mínimo 30 minutos diários de atividades físicas, de forma contínua; use as escadas em vez de usar elevador; nos momentos livres faça uma caminhada, pratique esportes, dance; escute música; faça passeios ao ar livre, em uma praça por exemplo; saia com amigos e também com familiares; reserve um tempo consigo mesmo. Atividades físicas proporcionam benefícios físicos e psicológicos, tais como: redução do peso corporal; controle dos níveis de açúcar no sangue, de colesterol, da pressão arterial; melhora da mobilidade das articulações dos membros; aumento da densidade óssea (previne a osteoporose); aumento da resistência física; ajuda no controle da depressão; melhora a qualidade do sono; mantém sua vontade e capacidade de fazer as coisas por si mesmo; evita o isolamento social; alivia o estresse diário; aumenta o bem-estar; melhora a sua auto-estima.")
 st.image("https://www.pontotel.com.br/wp-content/uploads/2022/05/saude-fisica-o-que-e-saude-fisica.jpg")
 st.write("Em dias ensolarados: Dê prioridade às horas mais frescas do dia e evite exposição prolongada ao sol; use sempre protetor solar nas áreas expostas ao sol; use óculos escuros e roupas claras (pois roupas escuras absorvem mais calor) e use chapéu ou boné para se proteger.")
 st.write("Ao Alimentar-se: Faça, no mínimo, cinco refeições ao dia (café da manhã, lanche, almoço, lanche e jantar), pois assim evitamos comer demais em outras horas do dia, coma frutas, legumes e verduras variados no dia a dia; evite refrigerantes e salgadinhos; beba pelo menos dois litros (6 a 8 copos dependendo do tamanho) de água por dia; faça as refeições em um local calmo e nunca assistindo televisão ou mexendo no celular; procure não descontar sua ansiedade ou ansiosidade na comida.")
 st.header("MALEFÍCIOS")
 st.write("Podemos dizer de algo que resume alguém é seu modo de vida, o que melhor explica são seus hábitos, comportamentos, suas características individuais e seus vícios. Todas estas características representam uma fração de suas personalidade, isso vem da natureza humana, e ela influencia e sempre vai influenciar na criação de seus hábitos, mesmo que nem sempre, como no caso em questão, eles são conscientes e bons para saúde.")
 st.write("E por esta razão, e o fato de não serem hábitos conscientes, não há motivos aparentes para se sentir culpado, a não ser, é claro, que você os identifique e escolha não tentar melhorar estes hábitos ou abandoná-los.")
 st.image("https://blog.imotbh.com.br/wp-content/uploads/2018/12/263524-conheca-os-maleficios-do-sedentarismo-para-a-saude-810x580.jpg")
 st.write("Ficar muito tempo sentado: Obviamente, há muitos casos em que trabalhadores ou estudantes não possuem muita liberdade de escolha para ficarem ou não, muitas horas sentados, Porém, este hábito é prejudicial à saúde pois com o tempo, diminui seu metabolismo, gerando assim, mais facilidade para ganho de peso. Para evitar isto, de hora em hora, se levante e se movimente por uns minutos, assim, manterá sua saúde mais estável.")
 st.write("Roer as Unhas: Este hábito é muito comum naquelas pessoas que sofrem com ansiedade no dia a dia, gerando uma vontade incontrolável de arrancar ou roer pedaços da unha, sem conseguir parar até que consiga se sentir satisfeito. Sua solução deve ser adquirida através de um tratamento com médicos, os principais problemas que isto pode causar são: Danificação dos dentes, ferimentos na pele ao redor dos dedos com possibilidade de infecção, e a possibilidade de contrair diversas doenças pelo contato com germes e bactérias presentes nos dedos e unhas.")
 st.image("https://www.unimedvtrp.com.br/wp-content/uploads/importacao-blog/170163876cdcdc9d0f0d1dc66133145a.jpg")
 st.write("Hora do sono: A regulagem de sono é algo muito essencial para nosso bem estar, o controle da energia do dia de hoje pode influenciar muito nas atividades de amanhã, portanto, ter uma boa noite de sono é crucial, em média de 7 a 8 horas já é ótimo. Afinal, com um sono desregulado pode acabar gerando diversos problemas como a dificuldade no aprendizado e absorção de conhecimento, aumento de pressão arterial, depressão, doenças cardíacas entre outros. Um ponto importante a ser citado é que o uso de celular antes de dormir também prejudica seu sono e saúde, os celulares atuais emitem luz azul (que é prejudicial), a recomendação é que o uso seja interrompido uma hora antes de se deitar.")
 st.image("https://bhtorax.com.br/wp-content/uploads/elementor/thumbs/24401027_s-ogjpsy50v39jgpijfdecyxhq3xbpmbdpftdpzpqvt4.jpg")
 st.write("Tabagismo: Conhecido mundialmente por ser o pior hábito dos maus hábitos, já que a prática de fumar afeta quase que todos os órgãos do corpo humano, gerando assim a possibilidade (que não é nada baixa) de causar doenças como AVC, Câncer, tuberculose, bronquite, enfisema, desregulagem no sistema imunológico entre outras. Mas estes riscos não se privam somente a quem fuma, mas também afetam as pessoas que convivem com fumantes, que são chamados de “fumantes passivos”. Este mau hábito é um dos mais difíceis de se abandonar, afinal, ele gera uma dependência e vício muito grande, muitas das pessoas que costumam fumar, em um pensamento positivo fumam 1 a 2 maços por dia, além de todos estas consequências, há o fator monetário envolvido a compra excessiva e diária de cigarro.")
if paginaSelecionada == 'ALIMENTAÇÃO':
 st.title('BENEFÍCIOS E VITAMINAS  DOS ALIMENTOS')
 st.write('A alimentação é um dos fatores mais importantes para melhorar a saúde. A alimentação ajuda a prevenir doenças que podem ser muito perigosas e até fatais. Já que estamos no assunto, vamos falar sobre alguns alimentos que podem ajudar a melhorar a sua saúde.')
 st.image("https://vitacheckup.com.br/wp-content/uploads/2019/07/alimenta%C3%A7%C3%A3o_900x600.png") 
 st.header('BANANA')
 st.write("A banana é uma excelente fonte de vitamina C, vitamina B6, antioxidantes, potássio, magnésio e fibras. A fruta é obrigatória caso queira uma fonte rápida de energia. Ela também auxilia no funcionamento do intestino, por serem ricas em fibras, o que auxilia no equilíbrio intestinal.")
 st.image("https://images.educamaisbrasil.com.br/content/banco_de_imagens/guia-de-estudo/D/banana-da-prata.jpg") 
 st.header('OS BENEFÍCIOS DA BANANA')
 st.subheader("Previne Doenças Cardiovasculares")
 st.write("Por ser rica em potássio, mineral que regula os batimentos cardíacos, garante o funcionamento dos músculos e também tem o potencial de controlar os efeitos do sódio no organismo, previne a hipertensão, um dos fatores de risco para infarto e doenças cardíacas.")
 st.subheader("Ajuda Nas Funções Cerebrais")
 st.write("O consumo regular de banana ajuda nas atividades celebrais, como raciocinar, manter a concentração e memorizar, de modo que, graças ao triptofano, um aminoácido essencial para a produção de serotonina, também reduz as chances de ser ter um derrame.")
 st.subheader("Auxilia O Bom Humor")
 st.write("Citando novamente a serotonina, esta tem função primordial no melhoramento do humor e da sensação de bem-estar. Vale ressaltar que a serotonina também é primordial para o controle da ansiedade e no tratamento de quadros de depressão.")
 st.subheader("Melhora O Sono")
 st.write("Vale ressaltar que um dos componentes presentes na banana é justamente a vitamina B6 em conjunto com o triptofano e o potássio, são excelentes para se manter um sono de qualidade, dessa forma é indicado que se coma ao menos 1(uma) banana antes de dormir")
 st.subheader("Traz Energia Para O Corpo E Reduz Cãibras")
 st.write("Graças a alta concentração de cálcio, do potássio e do magnésio, a banana reduz as dores musculares e, em conjunto com boa hidratação, pode evitar as câimbras, forte contração involuntária do músculo, ressalta ainda que graças a quantidade de carboidratos na fruta, ela também é indicada como opção de consumo antes do treino por trazer muita energia")
 st.subheader("Aumenta A Saciedade E Contribui Com A Perda De Peso")
 st.write("Graças a alta quantidade de fibras presentes na fruta em questão, a banana é capaz de desacelerar o esvaziamento gástrico, trazendo assim uma maior sensação de saciedade que combinado com outros alimentos ricos em fibras se torna um forte aliado na perda de peso")
 st.subheader("Benéfica Ao Sistema Digestivo")
 st.write("Fora a sensação de saciedade, a fruta tem capacidade de reequilibrar a flora intestinal, ajudando na integridade da mucosa intestinal, e juntamente das fibras, a banana-verde possui amido, o que melhora o trânsito intestinal")
 st.subheader("Faz Bem Para A Visão")
 st.write("Graças a vitamina A e vitamina C a fruta faz muito bem para a saúde dos olhos, ressalvo que uma alimentação carente de vitamina A pode causar um problema ocular chamado nictalopia, conhecido como cegueira noturna, o qual é a dificuldade de enxergar à noite ou em ambientes com baixa luminosidade")
 st.header("GOIABA")
 st.write("A goiaba é um fruto rico em antioxidantes, substâncias que têm a capacidade de proteger as nossas células contra possíveis mazelas originarias do nosso próprio organismo, dessa forma, a goiaba ajuda na prevenção de doenças como câncer, doenças degenerativas e doenças cardiovasculares. Ademais é um alimento rico em fibras.")
 st.image("https://diariodonordeste.verdesmares.com.br/image/contentid/policy:1.3173474:1640185368/Goiabas-capa.jpg?f=default&$p$f=c702a3d")
 st.subheader("OS BENEFÍCIOS DA GOIABA")
 st.subheader("Fortalece O Sistema Imunológico ")
 st.write("Graças à sua abundância de vitamina C, a goiaba é um forte aliado para o aumento da nossa imunidade, combatendo bactérias e infecções virais")
 st.subheader("Combate Ao Câncer")
 st.write("A goiaba pode ser de certa ajuda na prevenção do câncer de mama, pulmão, próstata, etc. Tudo isso graças à sua composição rica em vitamina C, polifenóis e licopeno")
 st.subheader("Intestino Saudável")
 st.write("A fruta, por ser rica em fibras, ajuda no combate a prisão de ventre, além de ser um aliado na perda de peso e no controle da glicemia, já que embora tenha muita fibra, a fruta possui poucas calorias")
 st.subheader("Controle Do Estresse")
 st.write("Devido à presença do magnésio na goiaba, esta pode ajudar na melhora do humor e redução dos níveis de estresse")
 st.subheader("Controle Do Açúcar No Sangue")
 st.write(" A goiaba possui uma substância chamada pectina, fibra solúvel, que atua de modo a controlar os níveis de açúcar presentes no sangue, além de ter um baixo índice glicêmico, o que ajuda a combater os picos de insulina")
 st.subheader("Previne E Combate Problemas Cardiovasculares")
 st.write("A goiaba possui o potencial de equilibrar as quantidades de potássio e sódio no organismo, ajudando na diminuição da pressão artérias, preservar a saúde no sistema cardiovascular, aumentar o colesterol bom (HDL), e baixar o colesterol LDL e os níveis de triglicerídeos")
 st.subheader("Saúde Ocular")
 st.write("Assim como a banana, a goiaba também possui muita vitamina A primordial para a prevenção da catarata, degeneração macular e cegueira noturna")
 st.header('BATATA DOCE')
 st.write('A batata-doce é um alimento rico em proteínas, com vitaminas A, E, C e do complexo B, baixo teor de gordura, fonte de antioxidantes e minerais como cálcio, zinco, magnésio e potássio.')
 st.image('https://i0.wp.com/comidadebebe.pt/wp-content/uploads/2020/12/Blog-Glossa%CC%81rio-3.png?resize=1080%2C675&ssl=1')
 st.subheader('BENEFÍCIOS DA BATADA DOCE') 
 st.subheader("Ajuda na Pele")
 st.write("A batata-doce contém uma boa quantidade de beta-caroteno, que é convertido em vitaminas no organismo. Rica em vitamina C, um antioxidante que protege as células do corpo, a batata-doce ajuda a eliminar rugas e a firmar a pele.")
 st.subheader("Fortalece o Intestino")
 st.write("A batata-doce auxilia o intestino em diversas coisas, como formar um bolo fecal e estimular a movimentação, e também atua como alimento para as bactérias do intestino, proporcionando assim um tratamento contra a prisão de ventre.")
 st.subheader("Previne A Diabete")
 st.write("Graças ao seu baixo índice glicêmico, a batata-doce ajuda a retardar a absorção do açúcar após as refeições. A batata doce é importante para prevenir o diabetes.")
 st.subheader("Ajuda No Ganho De Massa")
 st.write("A batata doce é muito utilizada em exercícios físicos por ser uma fonte de energia. É rico em fibras, sendo uma das melhores opções para quem planeja fazer algum tipo de exercício.")
 st.subheader("Previne Doenças")
 st.write("A batata-doce contém um tipo de antioxidante que melhora a função dos vasos sanguíneos, chamado antocianinas, que reduzem o acúmulo de placas de gordura nas artérias. A batata-doce também ajuda a prevenir doenças como derrame, ataque cardíaco e aterosclerose, pois  reduz o colesterol no sangue.")
 st.header('LARANJA')
 st.write("A laranja é uma fruta de origem do continente asiático e muito bem adaptada à região brasileira, é uma fruta rica em vitamina C e também vários outros nutrientes como cálcio, magnésio, fibras e potássio")
 st.image('https://super.abril.com.br/wp-content/uploads/2016/12/laranja_home.jpg?quality=70&strip=all')
 st.subheader("BENEFÍCIOS DA LARANJA")
 st.subheader("Ajuda No Sistema Imunológico")
 st.write("A laranja possui vitaminas que desempenham um papel fundamental na estimulação da produção de glóbulos brancos. Os glóbulos brancos são um tipo de célula de defesa que combate infecções.")
 st.subheader("Saúde Dos Olhos")
 st.write("A laranja contém beta-caroteno, precursor da vitamina A, muito importante para a manutenção da visão. Promove a saúde ocular e previne problemas como olhos secos e cegueira noturna")
 st.subheader("Previne A Anemia")
 st.write("Por ser rica em vitamina C e ácido cítrico, a laranja ajuda a prevenir a anemia porque essas propriedades aumentam a absorção do ferro dos alimentos. A composição das laranjas também contém folato, que provoca a formação de glóbulos vermelhos saudáveis. ajuda a prevenir a anemia.")
 st.subheader("Controla A Pressão alta")
 st.write("A laranja contém muito potássio, mineral que aumenta o relaxamento dos vasos sanguíneos, o que facilita a circulação do sangue, reduz a pressão arterial, o que é muito útil para pessoas com hipertensão.")
if paginaSelecionada == 'EXERCÍCIOS':
 st.title("EXERCÍCIOS FÍSICOS")
 st.write("Atos que estão presentes no dia a dia das pessoas desde o dia em que nasceram, porém, muitas das vezes não são muito perceptíveis ou relevantes o bastante por grande parte da população. E é por este motivo que há inúmeros casos de sedentarismo, obesidade e alto nível de açúcar no sangue, por exemplo, doenças que são o reflexo de toda a falta de exercícios físicos de média/alta intensidade na rotina de todos. A prática de exercícios físicos de alta intensidade tem grande impacto na vida das pessoas, pois melhora em diversos aspectos a qualidade de vida, uma forma de entender isto mais facilmente é que compreendam que um exercício físico de alta intensidade permite que o corpo trabalhe mais em menos tempo, ou seja, não é uma atividade que tomará muito tempo do seu dia, podendo se encaixar na rotina de qualquer indivíduo e também pode aumentar seu fluxo sanguíneo, oxigenação e é claro, sua força muscular. Veja alguns exemplos a seguir.")
 st.subheader("FLEXÃO")
 st.write("Exercícios para peito, ombros e braços. Para faz a flexão é necessário manter a cabeça alinhada ao corpo e ao quadril, formando uma linha reta; Dobre os cotovelos e quase retorne à posição inicial do movimento sem encostar o corpo no chão")
 st.image("https://static.wixstatic.com/media/3bf1d9_d4fc1d2682ce43a5a9002fac3faa24ff~mv2.gif")
 st.write('- Sugestão: Faça 3 séries de 15 repetições')
 st.subheader("ABDOMINAL")
 st.write("Como o nome sugere, os abdominais fortalecem os músculos abdominais. Sente-se e flexione os joelhos, apoiando bem os pés no chão, coloque as mãos atrás da cabeça e desça o tronco suavemente, eleve o tronco, contraindo a musculatura do abdômen, desça novamente o tronco, devagar, desenrolando a coluna.")
 st.image("https://www.mundoboaforma.com.br/wp-content/uploads/2021/04/abdominal.gif")
 st.write('- Sugestão: faça 3 séries de 30 repetições')
 st.subheader("AGACHAMENTO")
 st.write("Trabalha os membros e os músculos inferiores. Para realizar o exercício deixe os pés afastados na largura dos ombros, a posição deve ser vertical e você deve sempre olhar para frente, agachar com movimentos máximos (como se estivesse sentado em uma cadeira) mas sem os calcanhares do chão e manter a barriga . Ao entrar, nunca deixe o joelho cruzar a linha dos dedos dos pés, volte à posição inicial e expire.")
 st.image("https://www.hipertrofia.org/blog/wp-content/uploads/2023/07/bodyweight-squat.gif")
 st.write('- Sugestão: faça 3 séries de 30 repetições')
 st.subheader("PRANCHA")
 st.write("A prancha fortalece os principais grupos musculares do core, incluindo o transverso, reto abdominal, oblíquos externos e glúteos. Para realizar o exercício, deite-se de bruços no chão, estique as pernas e junte os pés, apoiando as palmas das mãos no chão, logo acima dos ombros. Contraia os músculos abdominais e glúteos, levante o corpo, estendendo os braços.")
 st.image("https://newlabsvita.com.br/wp-content/uploads/2017/08/Prancha-Treinamento-Funcional.jpg")
 st.write('- Sugestaõ: faça 3 séries de 1 minuto')
 st.subheader("CORRER")
 st.write("Correr ajuda a perder peso, tonificar as coxas, manter a forma e melhorar a resistência muscular. Para começar a correr é preciso aquecer os músculos, manter o equilíbrio entre caminhar e correr, manter os braços e, portanto, os ombros relaxados, sentir os limites e aumentar gradativamente o ritmo.")
 st.image("https://www.smartfit.com.br/news/wp-content/uploads/2020/01/como-comec%CC%A7ar-a-correr.jpg")
 st.write('- Sugestão: correr por 12 minutos')
if paginaSelecionada == 'DIETAS':
 st.title('TIPOS DE ALIMENTAÇÃO PARA DIETA')
 st.header("SUGESTÃO DE DIETA DIÁRIA")
 st.subheader("07:00 CAFÉ DA MANHÃ")
 st.write('- 2 fatias de pão de forma de trigo integral (50 g)')
 st.write('- 1 colher de chá cheia de pasta de amendoim (8 g)')
 st.write('- 2 unidades grandes de ovo, galinha, inteiro, cozido, mexido (122 g) ou 3 fatias de pão de forma de trigo integrai (175 g) ou 2 copos de suco concentrado de uva, envasado (400 g)')
 st.write('- 1 xicarade chá cheia de café com leite (200 g)')
 st.write('- 1 fatia de mamão Papaia cru (170 g)')
 st.write('- 3 unidades grandes de ovo, galinha, inteiro, cozido, mexido (183 g)')
 st.subheader("10:00 LANCHE DA MANHÃ")
 st.write("- 3 unidades de castanha do pará (12 g)")
 st.write("- 4 colheres de sopa chelas de granola (44 g)")
 st.write("- 1 unidade pequena de iogurte natural (200 g)")
 st.subheader("12:00 ALMOÇO")
 st.write("- 100 gramas de salada ou verdura crua, exceto de fruta")
 st.write("- 1 colher de sopa de azeite de oliva extra virgem (8 g)")
 st.write("- 1 fatia média de tomate (15 g)")
 st.write("- 1 prato raso cheio, picada de alface americana crua (80 g)")
 st.write("- 1 colher de sopa cheia, ralada de cenoura crua (12 g)")
 st.write("- 5 colheres de sopa cheias de arroz integral cozido (100 g)")
 st.write("- 3 colheres de sopa de feijão carioca cozido (45 g)")
 st.subheader("16:00 LANCHE DA TARDE")
 st.write("- 2 fatias de pão de forma de trigo integral (50 g)")
 st.write("- 1 colher de sopa chela de queijo requeljão cremoso (30 g)")
 st.write("- 200 gramas de queijo mussarela light")
 st.write("- 1 fatia média de presunto (15 g)")
 st.write("- 1 copo de suco concentrado de uva, envasado (200 g)")
 st.subheader("19:00 JANTA")
 st.write("- 1 unidade pequena de pelto de frango, sem pele, grelhado (140 g)")
 st.write("- 100 gramas de legumes")
 st.write("- 2 conchas médias cheias de arroz integral cozido (234 g)")
 st.write("- 3 colheres de sopa de feijão carioca cozido (45 g)")
 st.subheader("22:00 CEIA")
 st.write("- 4 colheres de sopa de ovo, galinha, inteiro, cozido, omelete (60 g)")
 st.write("- 2 copos pequenos cheios de salada de frutas (300 g)")
 st.write("- 1 unidade media de iogurte, variedade de fraitas, sem gordura (170 g)")
 st.write('')
 st.header("LANCHE PARA GANHO DE MASSA MAGRA")
 st.write('')
 st.subheader("Sugestão 1")
 st.write("- O batata doce cozida com filé de frango grelhado ou atum em lata;")
 st.subheader("Sugestão 2")
 st.write("- Omelete com 4 claras e 1 gema misturados com 3 colheres de aveia integral;") 
 st.subheader("Sugestão 3")
 st.write("- Pão integral com uma fatia de filé de frango grelhado, com suco de laranja sem açúcar;")
 st.subheader("Sugestão 4")
 st.write("- Iogurte desnatado zero açúcar (do sabor que você preferir), com granola sem adição de açúcar;")
 st.subheader("Sugestão 5")
 st.write("- Banana amassada e misturada à aveia, salpicada com semente de linhaça ou chia, eleite desnatado ou de soja (para as mulheres) sem adição de açúcar;")
 st.subheader("Sugestão 6")
 st.write("- Banana assada com canela e queijo e açúcar")
 st.subheader("Sugestão 7")
 st.write("- Salada de fruta com chia, granola ou linhaça, adoçada com mel.")
 st.subheader("Sugestão 8")
 st.write("- 200ml de soja original batida com 5 morangos, 2 fatias de pão integral com duas fatias de queijo frescal light, 2 fatias de tomate com uma pitada de orégano.")
 st.subheader("Sugestão 9")
 st.write("- 170g de iogurte desnatado (1 pote), 4 torradas integrais e 2 ovos mexidos")
 st.subheader("Sugestão 10")
 st.write("- 2 barras de fruta de banana-passa, ameixa, goiaba ou cupuaçu")